# Generated by Django 4.0.3 on 2022-05-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userragistation',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('Designation', models.TextField()),
                ('password', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
