# Generated by Django 4.0.3 on 2022-05-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userragistation',
            name='Designation',
            field=models.TextField(default='student'),
        ),
        migrations.AlterField(
            model_name='userragistation',
            name='mobile',
            field=models.IntegerField(default='9161153581'),
        ),
        migrations.AlterField(
            model_name='userragistation',
            name='photo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
