# Generated by Django 4.0.3 on 2022-05-05 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_userragistation_added_on_userragistation_github_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.IntegerField(default='9161153581')),
                ('Designation', models.TextField(default='student')),
                ('photo', models.ImageField(default='', upload_to='')),
                ('twitter', models.CharField(default='@twiter', max_length=250)),
                ('github', models.CharField(default='@github', max_length=250)),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_on', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
